### ISSUE TITLE
Plugin looks for chrome bookmarks in Brave location

### ISSUE THREAD

**Issue by alexhwoods** [dhruvmanila/telescope-bookmarks.nvim#4]
thank you for the awesome plugin!

I can't seem to get the  plugin working consistently; I'm now reliably getting this error.

```
No Google Chrome bookmarks file found at: /Users/alexwoods/Library/Application Support/BraveSoftware/Br
ave-Browser/Default/Bookmarks
```

Here's my config
```
require('telescope').load_extension('bookmarks')

require('telescope').setup {
  extensions = {
    bookmarks = {
      selected_browser = 'google_chrome',
    },
  }
}

```

Even this Ex command gets that error:
```
:lua require('telescope').extensions.bookmarks.bookmarks({selected_browser='google_chrome'})
```

The only real difference I see between this and the documentation is the added `{` after the word extensions; I was thinking that's syntax error.

## My Setup
- plugin commit `eef8e53`
- Neovim version `v0.5.1`
- MacOS Big Sur, Version 11.2

**Comment by alexhwoods** [comment]
Ok I can confirm this is a configuration issue — I forked the project and set the default to chrome and then it worked.

Not sure how to configure it though

**Comment by alexhwoods** [comment]
Also realized a good way to test your configuration is to give a browser that is not supported, like `foo`. You should get an error like `"Unsupported browser: foo"`

**Comment by dhruvmanila** [comment]
> thank you for the awesome plugin!

Thanks. Good to hear this is useful :)

The error message is a bit misleading which I need to correct, but the extension is working fine. The problem is in the _order_ in which you're calling the functions, if that's exactly how you're configuring. Telescope `setup` should be done first and then you would want to load the extension so that the extension can see the user's configuration values.

Try this:
```lua
require('telescope').setup {
  extensions = {
    bookmarks = {
      selected_browser = 'google_chrome',
    },
  }
}

require('telescope').load_extension('bookmarks')
```

If this is still not working, please do tell.

**Comment by alexhwoods** [comment]
Ahh, perfect thank you!

And yeah, it's a cool extension. Nice work!
