### ISSUE TITLE
Raindrop backend configured for Telescope not working when plugin called as Neovim command within an Alacritty context

### ISSUE THREAD

**Issue by pmatulis** [dhruvmanila/telescope-bookmarks.nvim#41]
Prior to moving to Raindrop I was using the Firefox backend via a system-wide keyboard shortcut:

`alacritty -e nvim -c 'Telescope bookmarks'`

This worked fine.

However, since changing to the Raindrop backend I get a blank Neovim screen (as if I simply called `nvim`).

Inside neovim, the command `Telescope bookmarks` works as expected. The Raindrop URLs are available.

**Comment by dhruvmanila** [comment]
Raindrop requires making API calls to the server which it does so in the background every time you open a Neovim session and then cache it for later use within the same Neovim session. Are you not seeing any notifications like https://github.com/dhruvmanila/browser-bookmarks.nvim/blob/06cfcb53bf3012792f36eb8eb6cd08f782c9b329/lua/browser_bookmarks/browsers/raindrop.lua#L110-L113 ?

**Comment by pmatulis** [comment]
@dhruvmanila Negative - I do not see any messages. It's as if I simply called `nvim` on the command line. Is there some verbose switch or logs to inspect that can help?

**Comment by dhruvmanila** [comment]
Do you use any notification plugin? If not, can you check `:messages`? I'm referring to the below message:

https://github.com/user-attachments/assets/ff5a8fa3-69de-42c1-bba0-76d7d27bdd45

Regardless, as mentioned the bookmarks aren't available as soon as you open Neovim because it'll first try to collect them using the API. Once it's collected, only then you'll be able to search through them which is why you don't see any telescope window as soon as you open Neovim with the command. This is an expected behavior.
